<?php

namespace Mgilet\NotificationBundle\Repository;

/**
 * NotifiableEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifiableEntityRepository extends \Doctrine\ORM\EntityRepository
{
    
   
    
    
  
    
    
}

