<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMotephv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMotephv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMotephv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMotephv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMotephv\appProdProjectContainer([
    'container.build_hash' => 'Motephv',
    'container.build_id' => '9c1cac37',
    'container.build_time' => 1596282966,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMotephv');
