<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAlfpufi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAlfpufi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAlfpufi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAlfpufi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAlfpufi\appProdProjectContainer([
    'container.build_hash' => 'Alfpufi',
    'container.build_id' => '8fb8fbfa',
    'container.build_time' => 1603287331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAlfpufi');
