<?php

namespace GincidentBundle\Repository;

/**
 * calculRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class calculRepository extends \Doctrine\ORM\EntityRepository
{
}
