<?php

namespace GincidentBundle\Repository;

/**
 * incidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class incidentRepository extends \Doctrine\ORM\EntityRepository
{
}
