<?php

namespace GincidentBundle\Repository;

/**
 * listintervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listintervenantRepository extends \Doctrine\ORM\EntityRepository
{
}
