<?php

namespace GincidentBundle\Repository;

/**
 * listagentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listagentRepository extends \Doctrine\ORM\EntityRepository
{
}
