<?php

namespace GincidentBundle\Repository;
use \GincidentBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
   
    
   public  function findOneByRole($role)
    {
        $query = $this->getEntityManager->createQueryBuilder("
                select c from GincidentBundle:User c 
                WHERE c.role=:role")->setParameter('role', $role);

        return $query->getResult();
    }
    
  
    
    
}
