<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGvl8ooa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGvl8ooa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGvl8ooa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGvl8ooa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGvl8ooa\appDevDebugProjectContainer([
    'container.build_hash' => 'Gvl8ooa',
    'container.build_id' => '9d0fbdd7',
    'container.build_time' => 1603294969,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGvl8ooa');
