<?php

namespace Proxies\__CG__\GincidentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class client extends \GincidentBundle\Entity\client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'id', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'name', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'prenom', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'adresse', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'code_postal', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'tel_fixe', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'tel_mobile', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'email', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'num_rue', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'nom_rue', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'date_creation'];
        }

        return ['__isInitialized__', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'id', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'name', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'prenom', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'adresse', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'code_postal', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'tel_fixe', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'tel_mobile', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'email', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'num_rue', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'nom_rue', '' . "\0" . 'GincidentBundle\\Entity\\client' . "\0" . 'date_creation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode_Postal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode_Postal', []);

        return parent::getCode_Postal();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function getNum_Rue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNum_Rue', []);

        return parent::getNum_Rue();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumRue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumRue', []);

        return parent::getNumRue();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom_Rue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom_Rue', []);

        return parent::getNom_Rue();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomRue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomRue', []);

        return parent::getNomRue();
    }

    /**
     * {@inheritDoc}
     */
    public function getDate_liv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate_liv', []);

        return parent::getDate_liv();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateliv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateliv', []);

        return parent::getDateliv();
    }

    /**
     * {@inheritDoc}
     */
    public function getTel_Fixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel_Fixe', []);

        return parent::getTel_Fixe();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelFixe', []);

        return parent::getTelFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function getTel_Mobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel_Mobile', []);

        return parent::getTel_Mobile();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelMobile', []);

        return parent::getTelMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function setCode_Postal($code_postal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode_Postal', [$code_postal]);

        return parent::setCode_Postal($code_postal);
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($code_postal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$code_postal]);

        return parent::setCodePostal($code_postal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTel_Fixe($tel_fixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel_Fixe', [$tel_fixe]);

        return parent::setTel_Fixe($tel_fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelFixe($tel_fixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelFixe', [$tel_fixe]);

        return parent::setTelFixe($tel_fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function setTel_Mobile($tel_mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel_Mobile', [$tel_mobile]);

        return parent::setTel_Mobile($tel_mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelMobile($tel_mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelMobile', [$tel_mobile]);

        return parent::setTelMobile($tel_mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setNum_Rue($num_rue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNum_Rue', [$num_rue]);

        return parent::setNum_Rue($num_rue);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumRue($num_rue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumRue', [$num_rue]);

        return parent::setNumRue($num_rue);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom_Rue($nom_rue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom_Rue', [$nom_rue]);

        return parent::setNom_Rue($nom_rue);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomRue($nom_rue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomRue', [$nom_rue]);

        return parent::setNomRue($nom_rue);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate_Creation($date_liv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate_Creation', [$date_liv]);

        return parent::setDate_Creation($date_liv);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($date_liv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$date_liv]);

        return parent::setDateCreation($date_liv);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
